/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import Model.Point;
import java.awt.Color;
import java.awt.Graphics;

/**
 *
 * @author macbook
 */
public class DrawPanel extends javax.swing.JPanel {
    private Point[] points = null;
    /**
     * Creates new form DrawPanel
     */
    public DrawPanel() {
        initComponents();
    }

    @Override
    public void paint(Graphics grphcs) {
        super.paint(grphcs);
        
        if (points == null) {
            return;
        } else {
            grphcs.setColor(Color.RED);
            
            for (int i = 0; i < points.length; ++i) {
                if(points[i] == null){
                    break;
                } else {
                    grphcs.drawRect(points[i].getX(), points[i].getY(), 1, 1);
                }
                
            }
            
            for (int i = 0; i < points.length; ++i) {
                if(points[i] == null){
                    break;
                } else {
                    if( i % 2 == 1){
                        grphcs.drawLine(points[i-1].getX(), points[i-1].getY(), 
                                points[i].getX(), points[i].getY());
                    }
                }
            }
        }       
    }    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

    /**
     * @param points the points to set
     */
    public void setPoints(Point[] points) {
        this.points = points;
    }
}
