/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import Model.Point;
import java.awt.Color;
import java.awt.Graphics;
import java.util.ArrayList;

/**
 *
 * @author macbook
 */
public class SegmentsIntersect extends javax.swing.JPanel {
    private ArrayList<Point> points = null;
    private boolean hasResult;
    /**
     * Creates new form SegmentsIntersect
     */
    public SegmentsIntersect() {
        initComponents();
    }

    @Override
    public void paint(Graphics grphcs) {
        super.paint(grphcs);
        
        if (points == null || points.size() == 0) {
            return;
        } else {
            grphcs.setColor(Color.RED);
            
            for (int i = 1; i < points.size(); i+=2) {
                grphcs.drawLine(points.get(i).getX(),
                                points.get(i).getY(),
                                points.get(i-1).getX(),
                                points.get(i-1).getY());
            }
            
            grphcs.drawLine(points.get(points.size()-1).getX(),
                                    points.get(points.size()-1).getY(),
                                    points.get(points.size()-1).getX(),
                                    points.get(points.size()-1).getY());
        }   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

    /**
     * @param points the points to set
     */
    public void setPoints(ArrayList<Point> points) {
        this.points = points;
    }

    /**
     * @return the hasResult
     */
    public boolean isHasResult() {
        return hasResult;
    }

    /**
     * @param hasResult the hasResult to set
     */
    public void setHasResult(boolean hasResult) {
        this.hasResult = hasResult;
    }
}
